src/main/java/com/sss/wc/entity/WebUser.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sss.wc.entity;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

/**
 *
 * @author pdhs-sp
 */
@Entity
public class WebUser implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(unique = true)
    String userName;
    String password;
    String name;
    String sname;
    String tname;
    String email;
    boolean active;
    @ManyToOne
    Item position;
    boolean executiveOfficer;
    @ManyToOne
    Institute institute;
    @ManyToOne
    Department department;
    @Transient
    String repeatPassword;

    public String getRepeatPassword() {
        return repeatPassword;
    }

    public void setRepeatPassword(String repeatPassword) {
        this.repeatPassword = repeatPassword;
    }
    
    

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }
    

    public Institute getInstitute() {
        return institute;
    }

    public void setInstitute(Institute institute) {
        this.institute = institute;
    }
    
    

    public String getSname() {
        return sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    public String getTname() {
        return tname;
    }

    public void setTname(String tname) {
        this.tname = tname;
    }

    public Item getPosition() {
        return position;
    }

    public void setPosition(Item position) {
        this.position = position;
    }

    public boolean isExecutiveOfficer() {
        return executiveOfficer;
    }

    public void setExecutiveOfficer(boolean executiveOfficer) {
        this.executiveOfficer = executiveOfficer;
    }
    

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
    
    
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof WebUser)) {
            return false;
        }
        WebUser other = (WebUser) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "lk.gov.sp.healthdept.td.WebUser[ id=" + id + " ]";
    }
    
}

src/main/java/com/sss/wc/controllers/EnumController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sss.wc.controllers;

import com.sss.wc.enums.DoseUnit;
import com.sss.wc.enums.DurationUnit;
import javax.faces.bean.ApplicationScoped;
import javax.inject.Named;
import com.sss.wc.enums.Gender;
import com.sss.wc.enums.Intervention;
import com.sss.wc.enums.ItemType;
import com.sss.wc.enums.Laterality;
import com.sss.wc.enums.Onset;
import com.sss.wc.enums.Privilege;
import com.sss.wc.enums.UlcerType;

/**
 *
 * @author User
 */
@Named
@ApplicationScoped
public class EnumController {

    /**
     * Creates a new instance of EnumController
     */
    public EnumController() {
    }

    public Onset[] getOnsets() {
        return Onset.values();
    }

    public Laterality[] getLateralities() {
        return Laterality.values();
    }

    public Laterality[] getLateralitiesWithoutOther() {
        Laterality[] ls = {Laterality.Right, Laterality.Left, Laterality.Bilateral};
        return ls;
    }

    public Gender[] getGenders() {
        return Gender.values();
    }

    public ItemType[] getItemTypes() {
        return ItemType.values();
    }

    public DurationUnit[] getDurationUnits() {
        return DurationUnit.values();
    }

    public DurationUnit[] getDurationDaysOrWeeks() {
        DurationUnit[] tds = {DurationUnit.Days, DurationUnit.Weeks};
        return tds;
    }
    
    
    public UlcerType[] getUlcerTypes() {
        return UlcerType.values();
    }

    public DoseUnit[] getDoseUnits() {
        return DoseUnit.values();
    }

    public Privilege[] getPrivileges() {
        return Privilege.values();
    }
    
    public Intervention[] getInterventions(){
        return Intervention.values();
    }
    
}

src/main/java/com/sss/wc/controllers/ItemController.java
package com.sss.wc.controllers;



import com.sss.wc.controllers.util.JsfUtil;
import com.sss.wc.controllers.util.JsfUtil.PersistAction;
import com.sss.wc.entity.Item;
import com.sss.wc.enums.ItemType;
import com.sss.wc.facades.ItemFacade;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("itemController")
@SessionScoped
public class ItemController implements Serializable {

    @EJB
    private com.sss.wc.facades.ItemFacade ejbFacade;
    private List<Item> items = null;
    private List<Item> dressings = null;
    private List<Item> investigations = null;
    private List<Item> medicines = null;
    
    
    private Item selected;

    public ItemController() {
    }

    public Item getSelected() {
        return selected;
    }

    public List<Item> getDressings() {
        if(dressings==null){
            dressings = fillItems(ItemType.Wound_dressing);
        }
        return dressings;
    }

    public void setDressings(List<Item> dressings) {
        this.dressings = dressings;
    }

    public List<Item> getInvestigations() {
        if(investigations==null){
            investigations = fillItems(ItemType.Investigation);
        }
        return investigations;
    }

    public void setInvestigations(List<Item> investigations) {
        this.investigations = investigations;
    }

    public List<Item> getMedicines() {
        if(medicines==null){
            medicines= fillItems(ItemType.Oral_medications);
        }
        return medicines;
    }

    public void setMedicines(List<Item> medicines) {
        this.medicines = medicines;
    }

    
    
    public void setSelected(Item selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ItemFacade getFacade() {
        return ejbFacade;
    }

    public Item prepareCreate() {
        selected = new Item();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle1").getString("ItemCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;
            dressings=null;
            medicines=null;
            investigations=null;
// Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle1").getString("ItemUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle1").getString("ItemDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
           dressings=null;
            medicines=null;
            investigations=null;
        }
    }

    public List<Item> getItems() {
        if (items == null) {
            items = fillItems();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle1").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle1").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Item getItem(java.lang.Long id) {
        return getFacade().find(id);
    }

    public List<Item> getItemsAvailableSelectMany() {
        return getItems();
    }

    public List<Item> getItemsAvailableSelectOne() {
        return getItems();
    }

    public List<Item> fillItems(ItemType itemType){
        String j="select i from Item i where i.itemType=:it order by i.name";
        Map m = new HashMap();
        m.put("it", itemType);
        return getFacade().findBySQL(j, m);
    }
    
    public List<Item> fillItems(){
        String j="select i from Item i order by i.name";
        return getFacade().findBySQL(j);
    }
    
    @FacesConverter(forClass = Item.class)
    public static class ItemControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ItemController controller = (ItemController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "itemController");
            return controller.getItem(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Item) {
                Item o = (Item) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Item.class.getName()});
                return null;
            }
        }

    }

}

src/main/webapp/webUser/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="WebUserCreateDlg" widgetVar="WebUserCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateWebUserTitle}">
            <h:form id="WebUserCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{webUserController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateWebUserLabel_userName}" for="userName" />
                        <p:inputText id="userName" value="#{webUserController.selected.userName}" title="#{bundle.CreateWebUserTitle_userName}" />
                        <p:outputLabel value="#{bundle.CreateWebUserLabel_password}" for="password" />
                        <p:inputText id="password" value="#{webUserController.selected.password}" title="#{bundle.CreateWebUserTitle_password}" />
                        <p:outputLabel value="#{bundle.CreateWebUserLabel_name}" for="name" />
                        <p:inputText id="name" value="#{webUserController.selected.name}" title="#{bundle.CreateWebUserTitle_name}" />
                        <p:outputLabel value="#{bundle.CreateWebUserLabel_email}" for="email" />
                        <p:inputText id="email" value="#{webUserController.selected.email}" title="#{bundle.CreateWebUserTitle_email}" />
                        <p:outputLabel value="Institution" for="ins" />
                        <p:selectOneMenu id="ins" value="#{webUserController.selected.institute}" > 
                            <f:selectItem itemLabel="Select" ></f:selectItem>
                            <f:selectItems value="#{instituteController.itemsAvailableSelectOne}" var="i" itemLabel="#{i.name}" itemValue="#{i}" ></f:selectItems>
                        </p:selectOneMenu>
                        <p:outputLabel value="Department" for="dept" />
                        <p:selectOneMenu id="dept" value="#{webUserController.selected.department}" > 
                            <f:selectItem itemLabel="Select" ></f:selectItem>
                            <f:selectItems value="#{departmentController.itemsAvailableSelectOne}" var="d" itemLabel="#{d.name}" itemValue="#{d}" ></f:selectItems>
                        </p:selectOneMenu>

                    </p:panelGrid>
                    <p:commandButton actionListener="#{webUserController.create}" value="#{bundle.Save}" update="display,:WebUserListForm:datalist,:growl" oncomplete="handleSubmit(args,'WebUserCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="WebUserCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/webUser/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="WebUserEditDlg" widgetVar="WebUserEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditWebUserTitle}">
            <h:form id="WebUserEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{webUserController.selected != null}">
                        <p:outputLabel value="#{bundle.EditWebUserLabel_userName}" for="userName" />
                        <p:inputText id="userName" value="#{webUserController.selected.userName}" title="#{bundle.EditWebUserTitle_userName}" />
                        <p:outputLabel value="#{bundle.EditWebUserLabel_password}" for="password" />
                        <p:inputText id="password" value="#{webUserController.selected.password}" title="#{bundle.EditWebUserTitle_password}" />
                        <p:outputLabel value="#{bundle.EditWebUserLabel_name}" for="name" />
                        <p:inputText id="name" value="#{webUserController.selected.name}" title="#{bundle.EditWebUserTitle_name}" />
                        <p:outputLabel value="#{bundle.EditWebUserLabel_email}" for="email" />
                        <p:inputText id="email" value="#{webUserController.selected.email}" title="#{bundle.EditWebUserTitle_email}" />
                        <p:outputLabel value="Institution" for="ins" />
                        <p:selectOneMenu id="ins" value="#{webUserController.selected.institute}" > 
                            <f:selectItem itemLabel="Select" ></f:selectItem>
                            <f:selectItems value="#{instituteController.itemsAvailableSelectOne}" var="i" itemLabel="#{i.name}" itemValue="#{i}" ></f:selectItems>
                        </p:selectOneMenu>  
                        <p:outputLabel value="Department" for="dept" />
                        <p:selectOneMenu id="dept" value="#{webUserController.selected.department}" > 
                            <f:selectItem itemLabel="Select" ></f:selectItem>
                            <f:selectItems value="#{departmentController.itemsAvailableSelectOne}" var="d" itemLabel="#{d.name}" itemValue="#{d}" ></f:selectItems>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{webUserController.update}" value="#{bundle.Save}" update="display,:WebUserListForm:datalist,:growl" oncomplete="handleSubmit(args, 'WebUserEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="WebUserEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/webUser/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="WebUserViewDlg" widgetVar="WebUserViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewWebUserTitle}">
            <h:form id="WebUserViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{webUserController.selected != null}">
                        <h:outputText value="#{bundle.ViewWebUserLabel_userName}"/>
                        <h:outputText value="#{webUserController.selected.userName}" title="#{bundle.ViewWebUserTitle_userName}"/>
                        <h:outputText value="#{bundle.ViewWebUserLabel_password}"/>
                        <h:outputText value="#{webUserController.selected.password}" title="#{bundle.ViewWebUserTitle_password}"/>
                        <h:outputText value="#{bundle.ViewWebUserLabel_name}"/>
                        <h:outputText value="#{webUserController.selected.name}" title="#{bundle.ViewWebUserTitle_name}"/>
                        <h:outputText value="#{bundle.ViewWebUserLabel_email}"/>
                        <h:outputText value="#{webUserController.selected.email}" title="#{bundle.ViewWebUserTitle_email}"/>
                        <h:outputText value="#{bundle.ViewWebUserLabel_id}"/>
                        <h:outputText value="#{webUserController.selected.id}" title="#{bundle.ViewWebUserTitle_id}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="WebUserViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/webUser/add_new_user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <body>

        <ui:composition template="./index.xhtml">

            <ui:define name="userimage">
                <p:graphicImage library="image" name="user_add.png" styleClass="sideImage" ></p:graphicImage>
            </ui:define>

            <ui:define name="manageusers">
                <p:panel header="Add New User" >
                    <h:form id="WebUserCreateForm">
                        <h:panelGroup id="display">
                            <p:panelGrid columns="2" rendered="#{webUserController.selected != null}">
                                <p:outputLabel value="#{bundle.CreateWebUserLabel_name}" for="name" />
                                <p:inputText id="name" value="#{webUserController.selected.name}" title="#{bundle.CreateWebUserTitle_name}" />

                                <p:outputLabel value="#{bundle.CreateWebUserLabel_userName}" for="userName" />
                                <p:inputText id="userName" value="#{webUserController.selected.userName}" title="#{bundle.CreateWebUserTitle_userName}" />
                                <p:outputLabel value="#{bundle.CreateWebUserLabel_password}" for="password" />
                                <p:password id="password" value="#{webUserController.selected.password}" title="#{bundle.CreateWebUserTitle_password}" />
                                <p:outputLabel value="#{bundle.PasswordAgain}" for="passwordr" />
                                <p:password id="passwordr" value="#{webUserController.selected.repeatPassword}" title="#{bundle.PasswordAgain}" />
                                
                                <p:outputLabel value="#{bundle.CreateWebUserLabel_email}" for="email" />
                                <p:inputText id="email" value="#{webUserController.selected.email}" title="#{bundle.CreateWebUserTitle_email}" />
                                <p:outputLabel value="Institution" for="ins" />
                                <p:selectOneMenu id="ins" value="#{webUserController.selected.institute}" > 
                                    <f:selectItem itemLabel="Select" ></f:selectItem>
                                    <f:selectItems value="#{instituteController.itemsAvailableSelectOne}" var="i" itemLabel="#{i.name}" itemValue="#{i}" ></f:selectItems>
                                </p:selectOneMenu>
                                <p:outputLabel value="Department" for="dept" />
                                <p:selectOneMenu id="dept" value="#{webUserController.selected.department}" > 
                                    <f:selectItem itemLabel="Select" ></f:selectItem>
                                    <f:selectItems value="#{departmentController.itemsAvailableSelectOne}" var="d" itemLabel="#{d.name}" itemValue="#{d}" ></f:selectItems>
                                </p:selectOneMenu>

                            </p:panelGrid>
                            <p:commandButton ajax="false"
                                             actionListener="#{webUserController.saveNewUser}"
                                             value="#{bundle.Save}" />
                        </h:panelGroup>
                    </h:form>
                </p:panel>
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/webUser/edit_user.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <body>

        <ui:composition template="./index.xhtml">

            <ui:define name="userimage">
                <p:graphicImage library="image" name="user_add.png" styleClass="sideImage" ></p:graphicImage>
            </ui:define>

            <ui:define name="manageusers">
                <p:panel header="Edit User - #{webUserController.selected.name}" >
                    <h:form id="WebUserCreateForm">
                        <h:panelGroup id="display">
                            <p:panelGrid columns="2" rendered="#{webUserController.selected != null}">
                                
                                <p:outputLabel value="#{bundle.CreateWebUserLabel_name}" for="name" />
                                <p:inputText id="name" value="#{webUserController.selected.name}" title="#{bundle.CreateWebUserTitle_name}" />

                                <p:outputLabel value="#{bundle.CreateWebUserLabel_userName}" for="userName" />
                                <p:inputText disabled="true" id="userName" value="#{webUserController.selected.userName}" title="#{bundle.CreateWebUserTitle_userName}" />
                                
                                <p:outputLabel value="Email" for="email" />
                                <p:inputText id="email" value="#{webUserController.selected.email}" title="#{bundle.CreateWebUserTitle_email}" />
                                
                                <p:outputLabel value="Institution" for="ins" />
                                <p:selectOneMenu id="ins" value="#{webUserController.selected.institute}" > 
                                    <f:selectItem itemLabel="Select" ></f:selectItem>
                                    <f:selectItems value="#{instituteController.itemsAvailableSelectOne}" var="i" itemLabel="#{i.name}" itemValue="#{i}" ></f:selectItems>
                                </p:selectOneMenu>
                                
                                <p:outputLabel value="Department" for="dept" />
                                <p:selectOneMenu id="dept" value="#{webUserController.selected.department}" > 
                                    <f:selectItem itemLabel="Select" ></f:selectItem>
                                    <f:selectItems value="#{departmentController.itemsAvailableSelectOne}" var="d" itemLabel="#{d.name}" itemValue="#{d}" ></f:selectItems>
                                </p:selectOneMenu>

                            </p:panelGrid>
                            <p:commandButton ajax="false"
                                             actionListener="#{webUserController.saveExistingUser}"
                                             value="#{bundle.Save}" />
                        </h:panelGroup>
                    </h:form>
                </p:panel>
            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/webUser/manage_privileges.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <body>

        <ui:composition template="./index.xhtml">



            <ui:define name="manageusers">

                <h:form >
                    <h:panelGrid columns="1" >
                        <p:panel header="Manage Privileges of #{userPrivilegeController.webUser.name}"  >
                            <p:panelGrid columns="3" >
                                <p:outputLabel value="Privilege" ></p:outputLabel>
                                <p:selectOneMenu value="#{userPrivilegeController.privilege}" >
                                    <f:selectItems value="#{enumController.privileges}" ></f:selectItems>
                                </p:selectOneMenu>
                                <p:commandButton value="Add Privilege" ajax="false" action="#{userPrivilegeController.addWebUserPrivilege()}" ></p:commandButton>
                            </p:panelGrid>
                            <p:dataTable value="#{userPrivilegeController.webUserPrivileges}" var="item">
                                <p:column width="150">
                                    <f:facet name="header">
                                        <h:outputText value="Privilege"/>
                                    </f:facet>
                                    <h:outputText value="#{item.privilege}"/>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">
                                        <h:outputText value="Action"/>
                                    </f:facet>
                                    <p:commandButton ajax="false" value="Remove Privilege" action="#{userPrivilegeController.removeUserPrivilege()}" >
                                        <f:setPropertyActionListener value="#{item}" target="#{userPrivilegeController.selected}" ></f:setPropertyActionListener>
                                    </p:commandButton>
                                </p:column>
                            </p:dataTable>


                        </p:panel>
                        <p:graphicImage library="image" name="user_view.png" styleClass="sideImage" ></p:graphicImage>

                    </h:panelGrid>

                </h:form>



            </ui:define>

        </ui:composition>

    </body>
</html>