src/main/java/com/sss/wc/entity/Encounter.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sss.wc.entity;

import com.sss.wc.enums.Intervention;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;

/**
 *
 * @author nilukagun
 */
@Entity
public class Encounter implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @ManyToOne
    Patient patient;
    @Temporal(javax.persistence.TemporalType.DATE)
    Date encounterDate;
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    Date encounterDateTime;
    boolean debridement;
    @Lob
    String debridementComments;
    @Lob
    String notes;
    Double costPerVisit;
    @Enumerated(EnumType.STRING)
    private Intervention intervention;
    
    
    

    
    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

   

    public Double getCostPerVisit() {
        return costPerVisit;
    }

    public void setCostPerVisit(Double costPerVisit) {
        this.costPerVisit = costPerVisit;
    }
    
    

    public boolean isDebridement() {
        return debridement;
    }

    public void setDebridement(boolean debridement) {
        this.debridement = debridement;
    }

    public String getDebridementComments() {
        return debridementComments;
    }

    public void setDebridementComments(String debridementComments) {
        this.debridementComments = debridementComments;
    }

   

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public Date getEncounterDate() {
        return encounterDate;
    }

    public void setEncounterDate(Date encounterDate) {
        this.encounterDate = encounterDate;
    }

    public Date getEncounterDateTime() {
        return encounterDateTime;
    }

    public void setEncounterDateTime(Date encounterDateTime) {
        this.encounterDateTime = encounterDateTime;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Encounter)) {
            return false;
        }
        Encounter other = (Encounter) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.sss.wc.entity.Encounter[ id=" + id + " ]";
    }

    public Intervention getIntervention() {
        return intervention;
    }

    public void setIntervention(Intervention intervention) {
        this.intervention = intervention;
    }

}

src/main/java/com/sss/wc/controllers/EncounterController.java
package com.sss.wc.controllers;

import com.sss.wc.entity.Encounter;
import com.sss.wc.controllers.util.JsfUtil;
import com.sss.wc.controllers.util.JsfUtil.PersistAction;
import com.sss.wc.facades.EncounterFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named
@SessionScoped
public class EncounterController implements Serializable {

    @EJB
    private com.sss.wc.facades.EncounterFacade ejbFacade;
    private List<Encounter> items = null;
    private Encounter selected;

    public EncounterController() {
    }

    public Encounter getSelected() {
        return selected;
    }

    public void setSelected(Encounter selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private EncounterFacade getFacade() {
        return ejbFacade;
    }

    public Encounter prepareCreate() {
        selected = new Encounter();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/BundleEnI").getString("EncounterCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/BundleEnI").getString("EncounterUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/BundleEnI").getString("EncounterDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Encounter> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/BundleEnI").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/BundleEnI").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Encounter getEncounter(java.lang.Long id) {
        return getFacade().find(id);
    }

    public List<Encounter> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Encounter> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Encounter.class)
    public static class EncounterControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            EncounterController controller = (EncounterController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "encounterController");
            return controller.getEncounter(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Encounter) {
                Encounter o = (Encounter) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Encounter.class.getName()});
                return null;
            }
        }

    }

}

src/main/java/com/sss/wc/controllers/EnumController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sss.wc.controllers;

import com.sss.wc.enums.DoseUnit;
import com.sss.wc.enums.DurationUnit;
import javax.faces.bean.ApplicationScoped;
import javax.inject.Named;
import com.sss.wc.enums.Gender;
import com.sss.wc.enums.Intervention;
import com.sss.wc.enums.ItemType;
import com.sss.wc.enums.Laterality;
import com.sss.wc.enums.Onset;
import com.sss.wc.enums.Privilege;
import com.sss.wc.enums.UlcerType;

/**
 *
 * @author User
 */
@Named
@ApplicationScoped
public class EnumController {

    /**
     * Creates a new instance of EnumController
     */
    public EnumController() {
    }

    public Onset[] getOnsets() {
        return Onset.values();
    }

    public Laterality[] getLateralities() {
        return Laterality.values();
    }

    public Laterality[] getLateralitiesWithoutOther() {
        Laterality[] ls = {Laterality.Right, Laterality.Left, Laterality.Bilateral};
        return ls;
    }

    public Gender[] getGenders() {
        return Gender.values();
    }

    public ItemType[] getItemTypes() {
        return ItemType.values();
    }

    public DurationUnit[] getDurationUnits() {
        return DurationUnit.values();
    }

    public DurationUnit[] getDurationDaysOrWeeks() {
        DurationUnit[] tds = {DurationUnit.Days, DurationUnit.Weeks};
        return tds;
    }
    
    
    public UlcerType[] getUlcerTypes() {
        return UlcerType.values();
    }

    public DoseUnit[] getDoseUnits() {
        return DoseUnit.values();
    }

    public Privilege[] getPrivileges() {
        return Privilege.values();
    }
    
    public Intervention[] getInterventions(){
        return Intervention.values();
    }
    
}

src/main/java/com/sss/wc/controllers/ImageController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sss.wc.controllers;

import com.sss.wc.entity.EncounterItem;
import com.sss.wc.entity.Patient;
import com.sss.wc.entity.Resource;
import java.io.ByteArrayInputStream;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import javax.inject.Inject;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 *
 * @author nilukagun
 */
@Named(value = "imageController")
@RequestScoped
public class ImageController {

    @Inject
    PatientController patientController;

    public PatientController getPatientController() {
        return patientController;
    }

    public void setPatientController(PatientController patientController) {
        this.patientController = patientController;
    }

    /**
     * Creates a new instance of ImageController
     */
    public ImageController() {
    }


    public StreamedContent getEncounterPhoto() {
        FacesContext context = FacesContext.getCurrentInstance();
        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            System.out.println("renderer response");
            // So, we're rendering the view. Return a stub StreamedContent so that it will generate right URL.
            return new DefaultStreamedContent();
        } else {
            System.out.println("NOT a renderer response");
            Resource ei = getPatientController().nextEncounterPhoto();
            System.out.println("ei = " + ei);
            if (ei == null) {
                System.out.println("3");
                return new DefaultStreamedContent();
            } else {
                System.out.println("4");
                if (ei.getId() != null && ei.getBaImage() != null) {
                    System.out.println("5");
                    return new DefaultStreamedContent(new ByteArrayInputStream(ei.getBaImage()), ei.getFileType(), ei.getFileName());
                } else {
                    System.out.println("6");
                    return new DefaultStreamedContent();
                }
            }
        }

    }
    
    public StreamedContent getWoundPhoto() {
        FacesContext context = FacesContext.getCurrentInstance();
        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            System.out.println("renderer response");
            // So, we're rendering the view. Return a stub StreamedContent so that it will generate right URL.
            return new DefaultStreamedContent();
        } else {
            System.out.println("NOT a renderer response");
            Resource ei = getPatientController().nextWoundPhoto();
            System.out.println("ei = " + ei);
            if (ei == null) {
                System.out.println("3");
                return new DefaultStreamedContent();
            } else {
                System.out.println("4");
                if (ei.getId() != null && ei.getBaImage() != null) {
                    System.out.println("5");
                    return new DefaultStreamedContent(new ByteArrayInputStream(ei.getBaImage()), ei.getFileType(), ei.getFileName());
                } else {
                    System.out.println("6");
                    return new DefaultStreamedContent();
                }
            }
        }

    }
    
    public StreamedContent getFirstWoundPhoto() {
        FacesContext context = FacesContext.getCurrentInstance();
        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            System.out.println("renderer response");
            // So, we're rendering the view. Return a stub StreamedContent so that it will generate right URL.
            return new DefaultStreamedContent();
        } else {
            System.out.println("NOT a renderer response");
            Resource ei = getPatientController().getFirstImage();
            System.out.println("ei = " + ei);
            if (ei == null) {
                System.out.println("3");
                return new DefaultStreamedContent();
            } else {
                System.out.println("4");
                if (ei.getId() != null && ei.getBaImage() != null) {
                    System.out.println("5");
                    return new DefaultStreamedContent(new ByteArrayInputStream(ei.getBaImage()), ei.getFileType(), ei.getFileName());
                } else {
                    System.out.println("6");
                    return new DefaultStreamedContent();
                }
            }
        }

    }
    
    
    public StreamedContent getLastWoundPhoto() {
        FacesContext context = FacesContext.getCurrentInstance();
        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            System.out.println("renderer response");
            // So, we're rendering the view. Return a stub StreamedContent so that it will generate right URL.
            return new DefaultStreamedContent();
        } else {
            System.out.println("NOT a renderer response");
            Resource ei = getPatientController().getLastImage();
            System.out.println("ei = " + ei);
            if (ei == null) {
                System.out.println("3");
                return new DefaultStreamedContent();
            } else {
                System.out.println("4");
                if (ei.getId() != null && ei.getBaImage() != null) {
                    System.out.println("5");
                    return new DefaultStreamedContent(new ByteArrayInputStream(ei.getBaImage()), ei.getFileType(), ei.getFileName());
                } else {
                    System.out.println("6");
                    return new DefaultStreamedContent();
                }
            }
        }

    }

}

src/main/webapp/patient/patient.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ez="http://java.sun.com/jsf/composite/ezcomp">

    <body>

        <ui:composition template="/template.xhtml">

            <ui:define name="title">
                Patient
            </ui:define>

            <ui:define name="body">
                <h:form>
                    <p:panel  style="margin: auto;width: 95%;" >
                        <f:facet name="header">
                            <p:outputLabel value="Patient Details" ></p:outputLabel>
                        </f:facet>
                        <h:panelGrid columns="7" >
                            <p:commandButton ajax="false" action="#{patientController.savePatient()}" value="Save" style="float: right;"></p:commandButton>
                            <p:spacer width="15"></p:spacer>
                            <p:commandButton ajax="false" action="#{patientController.saveAndNewWound()}" value="Add New Wound" style="float: right;"></p:commandButton>
                            <p:commandButton ajax="false" action="#{patientController.saveAndNewVisit()}" value="Add New Visit" style="float: right;"></p:commandButton>
                            <p:spacer width="15"></p:spacer>
                            <p:commandButton ajax="false" rendered="false" action="#{patientController.toSearchPatient()}" value="Search Patients" style="float: right;"></p:commandButton>
                        </h:panelGrid>
                        <p:panelGrid columns="3" styleClass="alignTop" style="width: 650px;" >
                            <h:panelGroup rendered="#{patientController.selected ne null}" >
                                <p:panelGrid columns="2" >
                                    <p:outputLabel value="Date of Registration:" for="dateOfRegistration" />
                                    <p:calendar id="dateOfRegistration"  pattern="dd MM yyyy"  value="#{patientController.selected.dateOfRegistration}" title="DateOfRegistration" >
                                    </p:calendar>

                                    <p:outputLabel value="Clinic Number:" for="clinicNumber" />
                                    <p:inputText id="clinicNumber" placeholder="[Generate a new number]"
                                                 value="#{patientController.selected.referenceNumber}" title="ClinicNumber" />

                                    <p:outputLabel value="Name of Patient:" for="nameOfPatient" />
                                    <p:inputText required="true" id="nameOfPatient" style="width: 300px;" value="#{patientController.selected.nameOfPatient}" title="NameOfPatient" />

                                    <p:outputLabel value="Gender:" for="gender" />
                                    <p:selectOneButton id="gender" value="#{patientController.selected.gender}"  label="Gender" required="true">
                                        <f:selectItems value="#{enumController.genders}" ></f:selectItems>
                                    </p:selectOneButton>
                                    <p:outputLabel value="Date of Birth:" for="dateOfBirth" />
                                    <h:panelGroup >
                                        <p:calendar yearRange="c-100:c" 
                                                    navigator="true" id="dateOfBirth" pattern="dd MM yyyy" value="#{patientController.selected.dateOfBirth}" title="DateOfBirth" required="true" >
                                            <p:ajax process="dateOfBirth" update="age" event="dateSelect"
                                                    listener="#{patientController.patientDobChanged}" ></p:ajax>
                                        </p:calendar>
                                        <p:spacer height="1" width="20" ></p:spacer>
                                        <p:outputLabel id="age" value="#{patientController.selected.age}"/>
                                    </h:panelGroup>

                                    <p:outputLabel value="Address:" for="address" />
                                    <p:inputTextarea rows="4" cols="30" id="address" value="#{patientController.selected.address}" title="Address" />


                                    <p:outputLabel value="Contact No.:" for="telephoneNoMobile" />
                                    <p:inputText id="telephoneNoMobile" value="#{patientController.selected.contactNumber }" title="TelephoneNoMobile" />


                                </p:panelGrid>

                            </h:panelGroup>
                            <h:panelGroup >

                                <h:panelGrid columns="1" style="min-width: 200px;" >

                                    <h:panelGroup rendered="#{empty patientController.selectedWounds}" >
                                        <p:outputLabel value="No Wounds Added Yet" ></p:outputLabel>
                                    </h:panelGroup>

                                    <h:panelGroup rendered="#{not empty patientController.selectedWounds}" >
                                        <p:tabView value="#{patientController.selectedWounds}" var="wo"   >
                                            <p:tab  title="#{wo.name}">
                                                <p:commandLink ajax="false" 
                                                               action="#{patientController.toViewWound()}" 
                                                               value="Click to View Details or Edit" >
                                                    <f:setPropertyActionListener target="#{patientController.selectedWound}" value="#{wo}" ></f:setPropertyActionListener>
                                                </p:commandLink>

                                                <ez:woundData wound="#{wo}"/>

                                            </p:tab>
                                        </p:tabView>






                                    </h:panelGroup>


                                    <p:dataTable value="#{patientController.selectedEncounters}" var="e" emptyMessage="No Visits"  >
                                        <p:column headerText="List of Visits" >
                                            <p:commandLink ajax="false" action="#{patientController.toViewEncounter()}" >
                                                <p:outputLabel value="#{e.encounterDateTime}"  >
                                                    <f:convertDateTime pattern="dd MMMM yyyy hh:mm" ></f:convertDateTime>
                                                </p:outputLabel>
                                                <f:setPropertyActionListener target="#{patientController.selectedEncounter}" value="#{e}" ></f:setPropertyActionListener>
                                            </p:commandLink>
                                        </p:column>
                                    </p:dataTable>
                                </h:panelGrid>
                            </h:panelGroup>
                            <h:panelGroup >
                                <p:commandButton value="View All Photos" action="/patient/patient_photos" ajax="false" ></p:commandButton>
                                <table >
                                    <tr>
                                        <td>
                                            <p:outputLabel value="First Photo">
                                            </p:outputLabel> 
                                        </td>
                                        <td>
                                            <p:outputLabel value="Last Photo"></p:outputLabel> 
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <p:graphicImage   
                                                id="photosFirst" cache="false" styleClass="sideImageResponsive" 
                                                rendered="#{imageController.firstWoundPhoto ne null}"    
                                                value="#{imageController.firstWoundPhoto}"  >
                                            </p:graphicImage>
                                        </td>
                                        <td>
                                            <p:graphicImage   
                                                id="photosLast" cache="false" styleClass="sideImageResponsive" 
                                                rendered="#{imageController.lastWoundPhoto ne null}"    
                                                value="#{imageController.lastWoundPhoto}"  >
                                            </p:graphicImage>
                                        </td>
                                    </tr>
                                </table>
                            </h:panelGroup>
                        </p:panelGrid>
                    </p:panel>
                </h:form>



            </ui:define>

        </ui:composition>

    </body>
</html>

src/main/webapp/patient/patient_photos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ez="http://java.sun.com/jsf/composite/ezcomp">

    <body>

        <ui:composition template="/template.xhtml">

            <ui:define name="title">
                Patient Photos
            </ui:define>

            <ui:define name="body">
                <h:form>
                    <p:panel  style="margin: auto;width: 95%;" >
                        <f:facet name="header">
                            <p:outputLabel value="Patient Photos" ></p:outputLabel>
                        </f:facet>

                        <p:panelGrid columns="1" styleClass="alignTop" style="width: 100%;" >
                            <p:commandButton value="Back to Patient" ajax="false" action="/patient/patient" ></p:commandButton>
                            <h:panelGroup >
                            <p:outputLabel  id="nameOfPatient" style="width: 300px;" value="#{patientController.selected.nameOfPatient}, " title="NameOfPatient" />
                            <p:outputLabel id="clinicNumber" 
                                           value=" #{patientController.selected.referenceNumber}" title="ClinicNumber" />
                            </h:panelGroup>
                            <h:panelGroup layout="block" style="width: 80%" >
                                <table>
                                    <tr>
                                        <td>
                                            <p:commandButton type="button" onclick="PF('switcher').previous();"
                                                             icon="ui-icon-circle-triangle-w" id="prev"/>
                                            <p:commandButton type="button" onclick="PF('switcher').next();"
                                                             icon="ui-icon-circle-triangle-e" id="next"/>
                                        </td>
                                        <td>
                                            
                                        </td>
                                        <td>
                                            
                                        </td>
                                    </tr>
                                </table>
                                <p:imageSwitch  style="width: 95vw;" widgetVar="switcher" effect="fade" slideshowAuto="false">
                                    
                                    <ui:repeat value="#{patientController.selectedWoundImages}"
                                               var="img"  >
                                        <table >
                                            <tr>
                                                <td>
                                                    <p:outputLabel value="#{img.wound.name}"></p:outputLabel> 
                                                    <p:spacer width="5"></p:spacer>
                                                    <p:outputLabel value="#{img.encounter.encounterDateTime}">
                                                        <f:convertDateTime pattern="dd MMMM yyyy hh:mm" ></f:convertDateTime>
                                                    </p:outputLabel> 
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <p:graphicImage   
                                                        id="photos" cache="false" style="width: 90vw;" 
                                                        rendered="#{img.baImage ne null}"    
                                                        value="#{imageController.woundPhoto }"  >
                                                    </p:graphicImage>
                                                </td>
                                            </tr>
                                        </table>
                                    </ui:repeat>
                                </p:imageSwitch>
                            </h:panelGroup>
                        </p:panelGrid>









                    </p:panel>
                </h:form>



            </ui:define>

        </ui:composition>

    </body>
</html>